### ISSUE TITLE
ChainerMN mnist and Chainer Mnist example speed test(Question)

### ISSUE THREAD

**Issue by luvwinnie** [chainer/chainermn#130]
Hi,I have installed ChainerMN in my docker environment. Under the Environment I have tried the normal chainer/example/train_mnist.py and chainermn/example/train_mnist.py

But I got the result of normal chainer faster training time compare to chainermn one.

(1)train_mnist.py on Nvidia-docker container with GTX TITAN GPU
<pre>
root@c620cda4aae6:~/chainer/examples/mnist# python train_mnist.py -g 0
/usr/local/lib/python2.7/dist-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 20

/usr/local/lib/python2.7/dist-packages/chainer/training/extensions/plot_report.py:25: UserWarning: matplotlib is not installed on your environment, so nothing will be plotted at this time. Please install matplotlib to plot figures.

  $ pip install matplotlib

  warnings.warn('matplotlib is not installed on your environment, '
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.190802    0.0801559             0.942267       0.9749                    3.11936
2           0.0740039   0.086214              0.976666       0.9739                    5.58505
3           0.0459295   0.0743716             0.985182       0.9765                    8.04036
4           0.0369725   0.0622468             0.987615       0.9813                    10.4912
5           0.0286685   0.109555              0.990565       0.9687                    12.9728
6           0.0232461   0.070821              0.992848       0.9812                    15.8562
7           0.0197429   0.0849811             0.993581       0.9777                    18.415
8           0.0180477   0.091499              0.993699       0.9778                    20.9872
9           0.0158452   0.0779782             0.994565       0.9824                    23.4289
10          0.0166323   0.100067              0.994432       0.9773                    26.0959
11          0.014609    0.0975057             0.995432       0.9813                    28.6492
12          0.0103739   0.109653              0.997016       0.9785                    31.4284
13          0.0134773   0.0936768             0.996082       0.983                     33.8616
14          0.0140495   0.0937355             0.995732       0.9821                    36.5562
15          0.0102782   0.0950652             0.997066       0.9812                    39.0016
16          0.0116389   0.106709              0.996849       0.9802                    41.5919
17          0.00899479  0.0889611             0.997449       0.982                     44.014
18          0.00671547  0.107222              0.998033       0.9808                    46.7314
19          0.0103872   0.115333              0.996899       0.9805                    49.1938
20          0.0115492   0.0843908             0.996966       0.9837                    51.805
</pre>

(2) Docker container with GTX TITAN and GTX 1080 two GPUs
<pre>
root@c620cda4aae6:~/chainermn/examples/mnist# mpiexec --allow-run-as-root -n 2 python train_mnist.py -g
/usr/local/lib/python2.7/dist-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
/usr/local/lib/python2.7/dist-packages/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
==========================================
Num process (COMM_WORLD): 2
Using GPUs
Using hierarchical communicator
Num unit: 1000
Num Minibatch-size: 100
Num epoch: 20
==========================================
epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  elapsed_time
1           0.228555    0.0938969             0.930967       0.9702                    5.05315
2           0.0781616   0.0802494             0.975968       0.9731                    8.25713
3           0.0495357   0.0608414             0.984067       0.981                     11.5505
4           0.0311331   0.0665458             0.99           0.9787                    14.7125
5           0.0218156   0.0729297             0.992267       0.9799                    17.9524
6           0.0225498   0.0836327             0.992167       0.9762                    20.999
7           0.017645    0.0783703             0.994533       0.9793                    24.3923
8           0.0150505   0.0763708             0.994833       0.9805                    27.2897
9           0.0126401   0.0751651             0.995334       0.983                     30.2712
10          0.014152    0.0800896             0.995633       0.9816                    33.1372
11          0.00949437  0.118996              0.996534       0.9738                    36.1006
12          0.00907453  0.0781274             0.997134       0.984                     38.9748
13          0.0125371   0.0901105             0.996          0.9798                    41.9752
14          0.0106789   0.0867079             0.996434       0.9817                    44.8528
15          0.0108346   0.0836941             0.996433       0.9813                    47.8183
16          0.00800829  0.100341              0.997233       0.9807                    51.5278
17          0.00982617  0.0995677             0.996633       0.9799                    55.3525
18          0.0044051   0.0925263             0.9988         0.983                     58.166
19          0.00590992  0.0931387             0.998367       0.9823                    61.0527
20          0.0067997   0.0864983             0.998233       0.983                     64.0285
</pre>

Why the training time is shorter in normal chainer with 1 gpu compare to 2 gpus?
Is this normal?

**Comment by shu65** [comment]
Hi @luvwinnie,
I think it is normal because MNIST data is small and the communication time is larger than computing time for training. Thanks.

**Comment by keisukefukuda** [comment]
I'm closing this issue. Please feel free to re-open it if you have further questions or issues.
