### ISSUE TITLE
Expand the abbreviation CPR

### ISSUE THREAD

**Issue by iwiwi** [chainer/chainermn#151]
In my opinion, abbrv `CPR` is not popular enough, and thus I would like to propose to change the method name `distributed_cpr`

**Comment by iwiwi** [comment]
In addition, we do not use `distributed` in our names. We use `multi_node` for some reason.

**Comment by kuenishi** [comment]
Agree. I'll change names to following manner:

```python
mn_checkpointer = create_multi_node_checkpointer(...)
mn_checkpointer.maybe_load()
while True:
  # Training loop
  mn_checkpointer.save()
```

**Comment by iwiwi** [comment]
Looks good to me 👍

**Comment by kuenishi** [comment]
New wordings are from PostgreSQL:
- https://www.postgresql.org/docs/9.2/static/wal-configuration.html
- https://github.com/postgres/postgres/blob/REL_10_1/src/backend/postmaster/checkpointer.c
