### ISSUE TITLE
Change class name `Alltoall` to `AllToAll`

### ISSUE THREAD

**Issue by iwiwi** [chainer/chainermn#154]
https://github.com/chainer/chainermn/blob/master/chainermn/functions/collective_communication.py

As MPI uses `MPI_Alltoall` for the function name, it is reasonable to use the class name `Alltoall`. On the other hand, `alltoall` is not a natural English expression. Indeed, we have `all_to_all` function below. Therefore, to be consistent with `all_to_all` function, I would like to change the class name to `AllToAll`.

**Comment by iwiwi** [comment]
Other way is to change `all_to_all` to `alltoall`. I would like to see consistency here anyway.

**Comment by levelfour** [comment]
Fixed to `AllToAll`, which I prefer.
