### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by Guriido** [chainer/chainermn#192]
In the tutorial part of the documentation, I found the following typos:

- In Step1: 
`In some applications, such as the ImageNet ChainerMN exmaple,` -> "exmaple" should be replaced by "example"

- In Step2: 
`The following line from the original MNIST example adds an evalautor extension` -> "evalautor" should be replaced by "evaluator"

**Comment by keisukefukuda** [comment]
Thanks for pointing out!
