### ISSUE TITLE
A beginner's question about the provided example

### ISSUE THREAD

**Issue by CSYShengyu** [chainer/chainermn#195]
In the example of mnist, e.g.  run `mpiexec -n 4 python train_mnist.py`, each node should start with the same initial parameters, then do their own bp, all reduce the gradient, the do the update, right?

But I think in the example, each node initializes a different param(LeCunNormal without random seed), is that a bug or we just intentionally do this?

**Comment by shu65** [comment]
Thank you. ChainerMN can work correctly even if each node start with the different parameters.
Because, ChainerMN communicates the parameters among all nodes in the first iteration so that they have the same parameters.

**Comment by CSYShengyu** [comment]
Aha, I got it.
