### ISSUE TITLE
Asynchronous Allreduce

### ISSUE THREAD

**Issue by arthuryuan1987** [chainer/chainermn#241]
Have you plan to support asynchronous allreduce ?
In current design (sync-allreduce), all nodes wait for allreduce result when gradient update. Have you plan to support async-allreduce ? Like,
Node-N `wait-allreduce-result` --> `layer-1-forward` --> `wait-allreduce-result` --> `layer-2-forward` --> `...` --> `layer-2-backward` --> `send-async-allreduce-request` -->`layer-1-backward` --> `send-async-allreduce-request`.

**Comment by keisukefukuda** [comment]
Currently, we don't have a plan to support it.  

(1) Communicating short-message over a network is very inefficient. Even if such communication-computation overlap improves the network hardware usage, it is not clear if it really improves the total computing time. 

(2) We have implemented a double-buffering feature in ChainerMN. This works in a similar manner, and the implementation is much simpler.

(3) We don't have a particular target application, that is expected to be accelerated with the technique and worth the implementation effort. We are happy to hear from you if you have such a target application!! (Maybe on Ethernet-environment or AWS?)

**Comment by keisukefukuda** [comment]
I'm closing the issue, but please feel free to reopen it if you have further questions or have more discussion on this. Thanks!
