### ISSUE TITLE
Manual selection for gpus in distributed training

### ISSUE THREAD

**Issue by 1292765944** [chainer/chainermn#269]
Note that different from other deep learning framework as MXNet, ChaineMN employs mpiexec for multi-gpu training. So how can I manually select certain gpus for training in ChainerMN?

**Comment by Guriido** [comment]
The traditional way to distribute your training is to use one MPI process for each GPU you want to use.
With mpiexec you can set the used nodes with the `hostfile` option:
```
$ mpiexec -hostfile your_hostfile python train.py
```

and your_hostfile should resemble this:
```
node1_ip_address slots=1
node2_ip_address slots=2
...
```

with the slots number set to the number of GPU on each node.

Your training script should then set the device to the intra_rank of communicator ( `device = comm.intra_rank` like in imagenet example).

If you want to use especially devices 0 and 2 (and not 1) on one node, you should precise this inside your python training script, for exemple with a loaded parameter file (which would be different for each node):
```py3
import json

with open('parameter.json') as json_data:
    parameters_dict = json.load(json_data)
    devices_to_use = parameters_dict['devices']  # which would be like devices to use as vector (e.g. [0, 2])
    device = devices_to_use[comm.intra_rank]
```

**Comment by 1292765944** [comment]
@Guriido  So the comm.intra_rank is accumulated from 0 automatically by default, right? Then we can manually reset the device_id accordingly in each MPI process.
By the way, how the comm.intra_rank is numbered among different nodes? can we use the comm.intra_rank on different nodes directly as gpu device_id.

**Comment by Guriido** [comment]
ChainerMN is based on mpi4py which is a python interface for MPI. If you are not familiar with the concepts, I suggest you to read some tutorials about communicators, and difference between intra and inter communicators. (for reference, mpy4py docs: https://mpi4py.scipy.org/docs/apiref/frames.html)

Roughly, and with default settings, the `comm.inter_rank` of a process will be unique for each MPI process, and the `comm.intra_rank` will be unique for each process **running on the same node**.

As in the [imagenet example](https://github.com/chainer/chainermn/blob/master/examples/imagenet/train_imagenet.py), you can indeed use `comm.intra_rank` on different nodes directly as gpu `device_id`.

> Then we can manually reset the device_id accordingly in each MPI process.

The good practice with MPI is to run the same (python) script on each node, so it is discouraged to set with hard code the devices you want to use on each node. If you want to use the GPU on each device with the order defined during installation, you have no need to worry about the settings, and should just use `comm.intra_rank`.
The example I showed earlier with `json` load was only in case you wanted to use *especially* certain devices (for example you have 3 GPU on a node, but for whatever reason the second one is broken and do inaccurate computation...).

**Comment by keisukefukuda** [comment]
@1292765944 , Thank you for your interest, and @Guriido thanks so much for your answers.
As @Guriido 's answers are really excellent, so there's not much left for me to answer.

Basically, you can do whatever you want about device IDs to use. If can also use host names if you need.

One thing I would add is that you can also utilize cuda-level features, including `CUDA_VISIBLE_DEVICES` for the sake of avoiding broken GPUs.

Thanks!

**Comment by 1292765944** [comment]
Ok, my problem is solved. Thanks for your help @Guriido  and @keisukefukuda !
