### ISSUE TITLE
optimizer.setup() created by create_multi_node_optimizer returns an original optimizer

### ISSUE THREAD

**Issue by rezoo** [chainer/chainermn#275]
I found a strange behavior that the current optimizer created by `chainermn.optimizers.create_multi_node_optimizer` returns the original optimizer. The example is as follows.
```python
import chainer
import chainermn

opt = chainer.optimizers.Adam()
link = chainer.links.Linear(10, 20)
opt.setup(link)  # returns <chainer.optimizers.adam.Adam at 0x7f8d97a81d30>
opt_multinode = chainermn.optimizers.create_multi_node_optimizer(opt, None)
opt_multinode.setup(link)  # returns <chainer.optimizers.adam.Adam at 0x7f8d97a81d30>
```

It seems that this behavior does not satisfy the specification required by chainer's optimizer.
I am not sure it should be fixed since modifying this specification will break backward compatibility, however, at least we should add this note on the manual.

**Comment by kuenishi** [comment]
Addressed by #292 and will be in 1.3.1 and next Chainer release.
