### ISSUE TITLE
Forcing forkserver spawn earlier

### ISSUE THREAD

**Issue by iwiwi** [chainer/chainermn#278]
With the recent change of the implementation inside NCCL, we need to force the initialization of the forkserver process earlier than the communicator initialization. So, we need to fix the example and the document.

https://github.com/chainer/chainermn/blob/master/examples/imagenet/train_imagenet.py#L172

**Comment by kuenishi** [comment]
One more todo: #290 was merged but should also be ported to Chainer.

**Comment by kuenishi** [comment]
1.3.1 diffs will be all ported later to Chainer.
