### ISSUE TITLE
CUDA streams usage

### ISSUE THREAD

**Issue by mshiryaev** [chainer/chainermn#287]
Hello,

As far as I see ChainerMN uses chainer.cuda.Stream.null for multi-gpu collective operations. This stream is mapped to default CUDA stream which is synchronized will all other streams. Is it correct understanding? Could you please clarify how computations and communications are overlapped and good scalability is achieved in such case?

**Comment by shu65** [comment]
Hi @mshiryaev, 
ChainerMN uses non-blocking cuda stream when computations and communications are overlapped.
https://github.com/chainer/chainermn/blob/master/chainermn/optimizers.py#L103-L105

Thanks.

**Comment by mshiryaev** [comment]
Hi @shu65, thanks for quick response.
Could you please comment how the dependencies are resolved between computation and communication?

I see this path for allreduce:
_DoubleBufferingOptimizer->update->allreduce_grad_async->nccl_allreduce(..., non_blocking_stream)

How allreduce waits for readiness of buffer to start communication and how SGD code waits for readiness of network buffer to start computation?

**Comment by shu65** [comment]
Hi @mshiryaev,

Allreduce and SGD code wait using `wait()` in  `_DoubleBufferingOptimizer`.
https://github.com/chainer/chainermn/blob/master/chainermn/optimizers.py#L93

It uses `synchronize()` of cuda stream used in Allreduce and default cuda stream to wait for Allreduce and SGD code to finish.

Thanks.

**Comment by mshiryaev** [comment]
@shu65 thanks, please comment on else one point.

I expect to find the following flow in the code: during back-prop for each gradient we wait completion on stream which is used for gradient calculation and start allreduce in separate stream that allows to overlap with back-props of other layers. In the end of iteration we do SGD which waits completion on allreduce stream and does SGD computation. How much ChainerMN flow differs from it?

As far as I see we do "wait" before each allreduce call, inside wait we synchronize on 2 streams so allreduce stream can execute only 1 allreduce at time. Is it correct understanding? Why not to execute multiple allreduce operations in this stream? Or actually this allreduce corresponds to multiple gradient buffers?


But if we synchronize on 2 streams in wait function then we

**Comment by keisukefukuda** [comment]
In the default settings, ChainerMN does not overlap communication and computation.
Everything happens in the default stream and synchronized implicitly.
For now, we don't see a significant performance issue without layer-wise allreduce.
@shu65 talked about double-buffing, which is a more-advanced feature of ChainerMN.

**Comment by mshiryaev** [comment]
@keisukefukuda thanks for clarification.
