### ISSUE TITLE
Creating trainer snapshots?

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainermn#76]
Does chainermn currently support some method of creating and resuming from a snapshot object?

I can see the `--resume` argument for the parser in the example files, but chainermn is unable to create a snapshot object when the snapshot extension is called.

Thanks

**Comment by iwiwi** [comment]
Thank you, we will work on this issue to support snapshot extensions.

FYI: Chainer's `snapshot` extension is known to be buggy. We sometimes use `snapshot_object` extension instead of `snapshot` extension, and resume the training by just loading model parameters dumped by `snapshot_object`.

**Comment by kuenishi** [comment]
With 1.1.0's checkpointing I think you can do most of what  you wanted to do. Also, I believe snapshot extension is stable enough as of today.

**Comment by keisukefukuda** [comment]
I'm closing the issue as the coordinated checkpointing feature of ChainerMN is stable and usable. Please feel free to reopen or create a new one if you have any further issues on this.
