### ISSUE TITLE
pickle and mpi error.. using chainercv with chainermn 

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainermn#88]
Hi,

I am trying to use chainercv with chainermn.

I used chainercv with some of my new projects and when i attempt to distribute training using chainermn, I receive the following error from the `scatter_dataset` method. All i am doing is applying a `random_flip` transform to the training data. I get the error for all my projects that use chainercv and have replicated it using the [chainermn mnist example file](https://gist.github.com/MannyKayy/a383b35d70124d7069e78255ed67b452) .

![image](https://user-images.githubusercontent.com/7952854/26975100-46ff5626-4d16-11e7-8ccc-6ab634541a66.png)

I'm not sure as to where to raise this issue so I have raised it in both the [chainercv](https://github.com/chainer/chainercv/issues/262) and chainermn repos.

**Comment by iwiwi** [comment]
What is the type of your dataset? (i.e., `train`). Method `scatter_dataset` requires it to be picklable.

**Comment by MannyKayy** [comment]
@iwiwi : so according to @yuyu2172 in the related [issue](https://github.com/chainer/chainercv/issues/262) on chainercv. 

> The error occurred because function objects can not be pickled.
We will look into a way to fix this issue. Thank you very much for reporting.

As can be seen on line 91 in [this gist](https://gist.github.com/MannyKayy/a383b35d70124d7069e78255ed67b452) the chainercv `TransformDataset` and `transform` functions wrap the dataset and carry out online data-augmentation. It seems they can't be pickled.

**Comment by iwiwi** [comment]
I see. Let me close this issue here, and let us continue the discussion at ChainerCV repository. Thanks!
