### ISSUE TITLE
test_allreduce_grad_gpu fails

### ISSUE THREAD

**Issue by levelfour** [chainer/chainermn#96]
It can be checked by the following test:
```
mpiexec -n 2 nosetests -v tests/test_communicator.py
```
This test sequence would stop at `test_allreduct_grad_gpu`. It seems `NcclCommunicator` has failed to initialize itself.

## Environment

MPI: __OpenMPI-2.1.0__ (do not reproduce on MVAPICH2-2.2)

**Comment by iwiwi** [comment]
It does not reproduce at the current master. Reopen this if it still happens at your environment. Thanks!
