### ISSUE TITLE
request for supporting for HDFS file system

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainermn#97]
Today, Hadoop filesystem is the most popular distributed file system in multiple machine.
Because Big Data need distributed file system to store, to train.
So hope chainer to support HDFS API to read data to train.

**Comment by keisukefukuda** [comment]
hi @sharpstill 
Thank you for your request. We will consider this carefully because it is better to be a Chainer's feature, rather than ChainerMN's. In addition, we have limited resource and we don't have much experience on Hadoop/HDFS unfortunately.

Thanks!

**Comment by sharpstill** [comment]
@keisukefukuda Thank you very much, HDFS can setup in only 2 machines to experiment.
By the way, tensorflow has already support HDFS and Yahoo release a tensorflow On spark version.
Maybe this will help you.

**Comment by kuenishi** [comment]
I wonder in what @sharpstill meant by supporting HDFS file system. Even today it is possible to just access data in HDFS;  by creating your own Dataset subclass that has list of files or chunks of HDFS file(s), and iterating over them at each `get_example()` call.  See [our example on local file system](https://github.com/chainer/chainermn/blob/v1.0.0/examples/imagenet/train_imagenet.py#L44-L82) and [Chainer's documentation on dataset](http://docs.chainer.org/en/stable/reference/core/dataset.html) . With these tools it's already possible to make your job directly read contents from HDFS. Also see [Wes McKinney's article on Python HDFS clients comparison](http://wesmckinney.com/blog/python-hdfs-interfaces/) for HDFS Python clients choice.

For further support such as data locality awareness and data access optimization, it needs various design decision and we'll be working on it.

**Comment by kuenishi** [comment]
So we're testing some use cases on HDFS but still not feeling the need to special code for HDFS, as we can make own Dataset accessor like [this](https://gist.github.com/kuenishi/0a705a0f46322ef69092aedd96b376f0#file-hdfs_image_dataset-py-L182-L227), using libhdfs and PyArrow. For the time being I'm closing this issue, but feel free to reopen for further discussion.
